name: Customies
description: A PocketMine-MP plugin that implements support for custom blocks, items and entities.

main: customiesdevs\customies\Customies
src-namespace-prefix: customiesdevs\customies
version: 1.2.0
api: 5.0.0

authors:
  - DenielWorld
  - TwistedAsylumMC
contributors:
  - JackNoordhuis
  - Unickorn
  - abimek

extensions:
  Core: >=8.1
